# Numpy and Pandas Homework


### Roland Chin

# NumPy Exercises

In [9]:
import numpy as np
import pandas as pd
import random

**Exercise 1:** Sum up all the odd numbers in `big_array`.

Hint: use a boolean array, this should only take 1 line.

In [10]:
big_array = np.arange(1, 193, 3)
big_sum = """YOUR CODE HERE"""
big_sum

'YOUR CODE HERE'

**Exercise 2:** Create a copy of `A` from `rand` and add it to the 3x3 identity matrix; `A` is shown below, but don't use `A` in your answer.

In [11]:
A = np.array([[-12, -13, 1], [-9, 15, 33], [-3, 1, -4]])
A

array([[-12, -13,   1],
       [ -9,  15,  33],
       [ -3,   1,  -4]])

In [12]:
np.random.seed(50) #this just makes it so everyone has the same random matrix
random = (np.random.randn(4, 6) * 10).astype(int)
random

array([[-15,   0,  -6, -14,  14,  -4],
       [ -7,  10, -12, -13,   1,   8],
       [  6,  -3,  -9,  15,  33,   9],
       [  1,   7,  -3,   1,  -4,  -1]])

In [13]:
"""YOUR CODE HERE"""

'YOUR CODE HERE'

**Exercise 3:** Select the 3x5 matrix at the top left corner of the `random` matrix above. Change this into a 1 dimensional vector, so that it can be appended to the element at the bottom right corner. Change this back into a 4x4 matrix afterwards, and find the average of this.

Hint: you will have to use `np.reshape` after getting the 3x5 matrix, and also after adding on the `-1`.

In [14]:
big_part = """YOUR CODE HERE"""
negative_1 = """YOUR CODE HERE"""

small_part = np.array([negative_1]) #this just puts -1 into an array so it can be appended to the vector big_part

combined = np.append(big_part, small_part)
square = """YOUR CODE HERE"""
square_mean = """YOUR CODE HERE"""
square_mean

'YOUR CODE HERE'

**Exercise 4:**  Remember how broadcasting eliminates the need `for` loops (see below example)?

In [15]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

Square every element of the following arrays `x` and `y`. Use broadcasting for `x`, and use a `for` loop for `y`.

Hint: you'll need to use `range` and `len` for the `for` loop.

In [16]:
x = np.array([3.0, 5.0, 8.0])
y = np.array([3.0, 5.0, 8.0])

#Square x here:
x = """YOUR CODE HERE"""

#Square y here:
for """YOUR CODE HERE"""
    """YOUR CODE HERE"""

SyntaxError: cannot assign to literal (3683139682.py, line 8)

**Exercise 5:** Say we have an 8x3 matrix, where the 3 columns represent 3 grocery stores (A, B, & C), and each row is the price for 8 items on our grocery list. We want to find which store will let you spend the least money.

Hint: remember the axis argument?

In [17]:
np.random.seed(30)
prices = np.absolute((np.random.randn(8, 3) * 10).astype(int))
prices

array([[12, 15,  9],
       [ 4,  1,  3],
       [17, 15,  1],
       [11, 15,  1],
       [ 7,  7, 13],
       [ 7,  2,  5],
       [20,  9,  0],
       [ 4,  4, 10]])

In [18]:
"""YOUR CODE HERE"""

'YOUR CODE HERE'

In [19]:
cheapest_store = """GROCERY STORE LETTER HERE"""

**Exercise 6:** Create a `vector` such that when added to `an_array`, returns the 3x3 identity matrix.

In [20]:
vector = """YOUR CODE HERE"""
an_array = np.array([[-2, -1, 3], [-3, 0, 3], [-3, -1, 4]])
identity = vector + an_array #does this look like np.eye(3, 3)?
identity

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U14'), dtype('int32')) -> None

**Exercise 7:** Create a vector `x` such that `x + y = z`.

In [ ]:
x = """YOUR CODE HERE"""
y = np.array([[3], [-2]])
z = np.array([[-4, 10], [-9, 5]])

In [ ]:
x + y #does this looke like z?

**Exercise 8:** We have 2 arrays, an array `x` consisting of some numbers and an array `y` consisting of letters that correspond to each number.

In [ ]:
x = np.array([-3, 1, 4, -9, 6, 4, 6, -2, -3, 5, 3, -5, 21, -3, 2, 1, -2, 3, 4, -3, 1, -2, -1])
x

In [ ]:
y = np.array(['s','e','r','u','z','u','i','s','a','e','s','i','p','s','e','s','c','w','b','o','m','o','l'])
y

Let's say we only want the letters whose corresponding numbers have a square root equal to 2. How would we do that?

In [21]:
"""YOUR CODE HERE"""

'YOUR CODE HERE'

**Exercise 9 (BONUS EXTRA CREDIT!!!):** In this problem, you will be using a bunch of the built in numpy operators for matrices. You don't have to do this if you don't already know linear algebra and numpy. We'll be covering it next week.

In [22]:
x, b = np.arange(1000).reshape(1000, 1), np.ones((1000, 1))

X = np.append(x, b, axis=1)
#all you need to know is that this is the X you will use in the equation below

Y = 2 * x[:,0] + 4*b + np.random.random()
#all you need to know is that this is the Y you will use in the equation below

Use Least Squares Linear Regression to solve for $\hat{\theta}$, the weights on each column of $X$ such that it models $Y$. Remember, the formula for Least Squares Linear Regression is: 

$$X^TX\hat{\theta} = X^TY$$

In [23]:
# theta_hat = np.linalg.solve(___, ___)
theta_hat

NameError: name 'theta_hat' is not defined

Find the loss of your model. The loss equation is as follows
$$ ||Y - X\hat{\theta}|| $$

Hint:
-  first find the difference of Y and the product of X and theta hat
-  use np.linalg.norm on this difference
-  square the result by multiplying that with itself (already filled in for you)
-  the answer should be 2.68e-18

In [24]:
# loss = np.dot(___, ___)
loss

NameError: name 'loss' is not defined

# Pandas Exercises

We'll be using the same Titanic dataset, which you've seen from lecture. It has the data for every passenger aboard the Titanic. We'll be looking at the training set (the training set is just a portion of the data upon which a model is fit, you'll learn more about this later).

In [25]:
titanic = pd.read_csv("train.csv")
titanic = titanic.set_index("PassengerId")
titanic.head(10)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C

**Exercise 10**: Calculate the average fare spent by males and females on the Titanic.

In [26]:
male = """YOUR CODE HERE"""
male_avg = """YOUR CODE HERE"""
male_avg

'YOUR CODE HERE'

In [27]:
female = """YOUR CODE HERE"""
female_avg = """YOUR CODE HERE"""
female_avg

'YOUR CODE HERE'

**Exercise 11:** Calculate the average age of those who survived and those who died on the Titanic.

In [28]:
survived = """YOUR CODE HERE"""
age_survived = """YOUR CODE HERE"""
age_survived

'YOUR CODE HERE'

In [29]:
died = """YOUR CODE HERE"""
age_died = """YOUR CODE HERE"""
age_died

'YOUR CODE HERE'

**Exercise 12:** Calculate the proportion of people who survived in each Pclass.

Hint: Use `len` to find the number of rows (passengers) in `survived_1` and `total_1`.

In [30]:
class_1 = """YOUR CODE HERE"""
survived_1 = """YOUR CODE HERE"""
total_1 = """YOUR CODE HERE"""
proportion_1 = survived_1 / total_1

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [31]:
class_2 = """YOUR CODE HERE"""
survived_2 = """YOUR CODE HERE"""
total_2 = """YOUR CODE HERE"""
proportion_2 = survived_2 / total_2

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [32]:
class_3 = """YOUR CODE HERE"""
survived_3 = """YOUR CODE HERE"""
total_3 = """YOUR CODE HERE"""
proportion_3 = survived_3 / total_3

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [33]:
print(proportion_1, proportion_2, proportion_3)

NameError: name 'proportion_1' is not defined

Do these values make logical sense?

![Titanic Pclasses](titanicpclass.jpg)

In [39]:
netflix = pd.read_csv("netflix_titles.csv")
netflix = netflix.set_index('show_id')
netflix.head(100)

type                                              title  \
show_id                                                               
s1         Movie                               Dick Johnson Is Dead   
s2       TV Show                                      Blood & Water   
s3       TV Show                                          Ganglands   
s4       TV Show                              Jailbirds New Orleans   
s5       TV Show                                       Kota Factory   
...          ...                                                ...   
s96      TV Show                                         The Circle   
s97        Movie  If I Leave Here Tomorrow: A Film About Lynyrd ...   
s98      TV Show                                         Kid Cosmic   
s99      TV Show                          Octonauts: Above & Beyond   
s100     TV Show                                       On the Verge   

                director                                               cast  \
show_id                                                                       
s1       Kirsten Johnson                                                NaN   
s2                   NaN  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   
s3       Julien Leclercq  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...   
s4                   NaN                                                NaN   
s5                   NaN  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...   
...                  ...                                                ...   
s96                  NaN                                    Michelle Buteau   
s97        Stephen Kijak  Ronnie Van Zandt, Gary Rossington, Allen Colli...   
s98                  NaN  Jack Fisher, Tom Kenny, Amanda C. Miller, Kim ...   
s99                  NaN  Antonio Aakeel, Chipo Chung, Simon Foster, Ter...   
s100                 NaN  Julie Delpy, Elisabeth Shue, Sarah Jones, Alex...   

                               country          date_added  release_year  \
show_id                                                                    
s1                       United States  September 25, 2021          2020   
s2                        South Africa  September 24, 2021          2021   
s3                                 NaN  September 24, 2021          2021   
s4                                 NaN  September 24, 2021          2021   
s5                               India  September 24, 2021          2021   
...                                ...                 ...           ...   
s96      United States, United Kingdom   September 8, 2021          2021   
s97                      United States   September 7, 2021          2018   
s98                      United States   September 7, 2021          2021   
s99                     United Kingdom   September 7, 2021          2021   
s100             France, United States   September 7, 2021          2021   

        rating   duration                                          listed_in  \
show_id                                                                        
s1       PG-13     90 min                                      Documentaries   
s2       TV-MA  2 Seasons    International TV Shows, TV Dramas, TV Mysteries   
s3       TV-MA   1 Season  Crime TV Shows, International TV Shows, TV Act...   
s4       TV-MA   1 Season                             Docuseries, Reality TV   
s5       TV-MA  2 Seasons  International TV Shows, Romantic TV Shows, TV ...   
...        ...        ...                                                ...   
s96      TV-MA  3 Seasons                                         Reality TV   
s97      TV-MA     97 min                    Documentaries, Music & Musicals   
s98      TV-Y7  2 Seasons         Kids' TV, TV Comedies, TV Sci-Fi & Fantasy   
s99       TV-Y   1 Season                         British TV Shows, Kids' TV   
s100     TV-MA   1 Season                             TV Comedies, TV Dramas   

                              

**Exercise 13.1**: Find the number of titles for each release year.

In [48]:
num_titles_per_year = """YOUR CODE HERE"""
num_titles_per_year

'YOUR CODE HERE'

**Exercise 13.2**: Find the max number of titles in a year.

In [49]:
"""YOUR CODE HERE"""

'YOUR CODE HERE'

**Exercise 13.3:** Find the average number of titles across all years.

In [50]:
"""YOUR CODE HERE"""

'YOUR CODE HERE'