# Answers to Exercises

In [42]:
import numpy as np
import pandas as pd
import random

**Exercise 1**

In [43]:
big_array = np.arange(1, 193, 3)
np.sum(big_array[big_array % 2 == 1])

3008

**Exercise 2**

In [46]:
A = np.array([[-12, -13, 1], [-9, 15, 33], [-3, 1, -4]])
np.random.seed(50) #this just makes it so everyone has the same random matrix
random = (np.random.randn(4, 6) * 10).astype(int)
random[1:5, 2:5] + np.eye(3, 3)

array([[-11., -13.,   1.],
       [ -9.,  16.,  33.],
       [ -3.,   1.,  -3.]])

**Exercise 3**

In [47]:
big_part = random[:3, :5].reshape((1, 15))
negative_1 = random[3][5]

small_part = np.array([negative_1]) #this just puts -1 into an array so it can be appended to the vector big_part

combined = np.append(big_part, small_part)
square = combined.reshape((4, 4))
square_mean = np.mean(square)
square_mean

-0.0625

**Exercise 4**

In [48]:
x = np.array([3.0, 5.0, 8.0])
y = np.array([3.0, 5.0, 8.0])

#Square x here:
x = x ** 2

#Square y here:
for i in range(len(y)):
    y[i] = y[i] ** 2

**Exercise 5:**

In [51]:
np.random.seed(30)
prices = np.absolute((np.random.randn(8, 3) * 10).astype(int))
prices.sum(axis=0)

array([82, 68, 42])

In [52]:
cheapest_store = "C"

**Exercise 6:**

In [53]:
vector = np.array([3, 1, -3])
an_array = np.array([[-2, -1, 3], [-3, 0, 3], [-3, -1, 4]])
identity = an_array + vector #does this look like np.eye(3, 3)?
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**Exercise 7:**

In [56]:
y = np.array([[3], [-2]])
z = np.array([[-4, 10], [-9, 5]])
x = np.array([-7, 7])

**Exercise 8:**

In [58]:
x = np.array([-3, 1, 4, -9, 6, 4, 6, -2, -3, 5, 3, -5, 21, -3, 2, 1, -2, 3, 4, -3, 1, -2, -1])
y = np.array(['s','e','r','u','z','u','i','s','a','e','s','i','p','s','e','s','c','w','b','o','m','o','l'])
y[np.sqrt(x) == 2]

C:\Users\ja343\AppData\Local\Temp\ipykernel_2504\2735090504.py:3: RuntimeWarning: invalid value encountered in sqrt
  y[np.sqrt(x) == 2]


array(['r', 'u', 'b'], dtype='<U1')

**Exercise 9:**

In [59]:
x, b = np.arange(1000).reshape(1000, 1), np.ones((1000, 1))

X = np.append(x, b, axis=1)
#all you need to know is that this is the X you will use in the equation below

Y = 2 * x[:,0] + 4*b + np.random.random()
#all you need to know is that this is the Y you will use in the equation below
theta_hat = np.linalg.solve((X.T @ X), (X.T @ Y))

In [60]:
loss = np.dot(np.linalg.norm(Y - (X @theta_hat)), np.linalg.norm(Y - (X @ theta_hat)))

**Exercise 10:**

In [17]:
# import titanic dataset
titanic = pd.read_csv("train.csv")
titanic = titanic.set_index("PassengerId")

In [18]:
male = titanic[titanic["Sex"] == "male"]
male_avg = male["Fare"].mean()
male_avg

female = titanic[titanic["Sex"] == "female"]
female_avg = female["Fare"].mean()
female_avg

44.47981783439487

**Exercise 11:**

In [19]:
survived = titanic[titanic["Survived"] == 1]
age_survived = survived["Age"].mean()
age_survived

28.343689655172415

In [20]:
died = titanic[titanic["Survived"] == 0]
age_died = died["Age"].mean()
age_died

30.62617924528302

**Exercise 12:**

In [21]:
class_1 = titanic[titanic["Pclass"] == 1]
survived_1 = len(class_1[class_1["Survived"] == 1])
total_1 = len(class_1)
proportion_1 = survived_1 / total_1

In [22]:
class_2 = titanic[titanic["Pclass"] == 2]
survived_2 = len(class_2[class_2["Survived"] == 1])
total_2 = len(class_2)
proportion_2 = survived_2 / total_2

In [23]:
class_3 = titanic[titanic["Pclass"] == 3]
survived_3 = len(class_3[class_3["Survived"] == 1])
total_3 = len(class_3)
proportion_3 = survived_3 / total_3

**Exercise 13.1**

In [24]:
# import netflix dataset
netflix = pd.read_csv("netflix_titles.csv")
netflix = netflix.set_index('show_id')

In [25]:
num_titles_per_year = netflix.groupby("release_year")[["title"]].count()
num_titles_per_year

title
release_year       
1925              1
1942              2
1943              3
1944              3
1945              4
...             ...
2017           1032
2018           1147
2019           1030
2020            953
2021            592

[74 rows x 1 columns]

**Exercise 13.2:**

In [35]:
num_titles_per_year['title'].max()

1147

**Exercise 13.3:**

In [40]:
num_titles_per_year['title'].mean()

119.01351351351352