# HW -- Lecture 6: Linear Algebra and Linear Regression

Given on March 29, 2022

## Linear Algebra

In [3]:
import numpy as np

**Exercise 1:** Create four different 4X1 vectors v1, v2, v3, and v4. 

In [4]:
v1= [4,5,2,7]
v2= [0,3,6,4]
v3= [9,7,3,2]
v4= [5,3,2,1]

**Exercise 2:** Create a 4X4 matrix called A using the vectors created in the previous exercise.

In [6]:
A = np.array([v1,v2,v3,v4])
print(A)

[[4 5 2 7]
 [0 3 6 4]
 [9 7 3 2]
 [5 3 2 1]]


**Exercise 3:** Find the specific transpose of the matrix A created above.

In [7]:
print(A.transpose())

[[4 0 9 5]
 [5 3 7 3]
 [2 6 3 2]
 [7 4 2 1]]


**Exercise 4:** Add matrix A to the transpose of the matrix B below.

In [8]:
B = np.array([[3,7,5,1],[4,0,3,1],[5,2,1,8],[7,3,2,0]])

print(A+B.transpose())

[[ 7  9  7 14]
 [ 7  3  8  7]
 [14 10  4  4]
 [ 6  4 10  1]]


**Exercise 5:** What is the dimensions of a 4X2 matrix times a 2X7 matrix?

In [9]:
ans='4X7'

**Exercise 6:** Are the rows of the matrices below linearly independent or dependent?

In [11]:
C = np.array([[5,3,7],[6,2,4],[-2,2,6]])
ans='Linearly dependent'

**Exercise 7:** Is the matrix C above invertible or not? Provide an explanation using the idea of linear independence or dependence.

Hint: Test using specific function given in the lecture

In [12]:
np.linalg.det(C)

0.0

Since the matrix C is linearly dependent, therefore one of the rows is a linear combination of the other rows, so the determinant of the matrix will be 0 resulting in the matrix being noninvertible